### ISSUE TITLE
Why use this standardization method in the Analytics?

### ISSUE THREAD

**Issue by fei161** [13o-bbr-bbq/machine_learning_security#21]
Why use 'x = (x-mean)/mean' standardization In line 15 of file analyze_kmeans.py?
Why not use max-min standardization or z-score standardization ？

**Comment by mbhatt1** [comment]
Shift the distribution to zero?

**Comment by 13o-bbr-bbq** [comment]
in my past experiment, accuracy of `x = (x-mean)/mean` is higher than max-min, z-score.  
but, i'll try to use max-min, z-score again.  
thanks for your advise!!
