### ISSUE TITLE
Illegal instruction 

### ISSUE THREAD

**Issue by shad0w12** [13o-bbr-bbq/machine_learning_security#44]
When I run  python3 main.py TRAIN I get the following error:
/$PATH/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using TensorFlow backend.
Illegal instruction

**Comment by 13o-bbr-bbq** [comment]
Did you install the TensorFlow?

**Comment by hamidb** [comment]
Probably your CPU does not support specific instructions against which Tensorflow is built. Like AVX, FMA, etc.
Try to find a .whl corresponding to your CPU architecture. Or build Tensorflow from source.
